async function home(){
 const ps=await api('/rest/v1/projects?select=*&order=name.asc');
 let h='<div class="wrap"><div class="hero"><div><h1>Projekti</h1><p class="sub">Izaberi projekat ili otvori Uputstvo</p></div><small class="sub">v'+APP_VERSION+'</small></div>';
 if(isAdmin())h+='<div class="adminbar"><b>Administracija</b><div class="btnrow"><button class="btn small" id="newProjectBtn">＋ Novi projekat</button><button class="btn sec small" id="usersBtn">Korisnici i prava</button></div></div>';
 h+='<div class="grid">';
 ps.forEach(p=>{h+='<div class="card" data-p="'+p.id+'"><h2>'+esc(p.name)+'</h2><p class="sub">'+esc(p.description||'')+'</p><b style="color:var(--blue)">Otvori →</b></div>'});
 h+='<div class="card guide-card" id="guideBtn"><div style="font-size:30px">📘</div><h2>Uputstvo</h2><p class="sub">Pravilnici, proračuni uključnih tačaka i ugradnja elemenata</p><b>Otvori Uputstvo →</b></div>';
 if(isAdmin())h+='<div class="card add-card" id="newProjectCard"><div style="font-size:36px">＋</div><h2>Novi projekat</h2><p class="sub">Dodaj novi projekat u centralnu evidenciju</p></div>';
 h+='</div></div>';shell(h);
 document.querySelectorAll('[data-p]').forEach(n=>n.onclick=()=>project(n.dataset.p));
 guideBtn.onclick=guideHome;
 if(isAdmin()){newProjectBtn.onclick=newProjectForm;newProjectCard.onclick=newProjectForm;usersBtn.onclick=manageUsers}
}
function slugifyProject(v){return (v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'dj').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)}
function newProjectForm(){let h='<div class="wrap"><button class="back" id="bh">← Projekti</button><h1>Novi projekat</h1><div class="form"><div class="field"><label>Naziv projekta</label><input id="npName" placeholder="Naziv projekta"></div><div class="field"><label>Kod / oznaka</label><input id="npCode" placeholder="npr. novi-projekat"></div><div class="field"><label>Kratak opis</label><textarea id="npDesc"></textarea></div><button class="btn" id="npSave">Kreiraj projekat</button><div id="npMsg" class="msg"></div></div></div>';shell(h);bh.onclick=home;npName.oninput=()=>{if(!npCode.dataset.edited)npCode.value=slugifyProject(npName.value)};npCode.oninput=()=>npCode.dataset.edited='1';npSave.onclick=saveNewProject}
async function saveNewProject(){const name=npName.value.trim(),code=slugifyProject(npCode.value||name),description=npDesc.value.trim()||null;if(!name||!code){npMsg.textContent='Unesi naziv i kod projekta.';npMsg.className='msg err';return}npSave.disabled=true;npMsg.textContent='Čuvanje...';try{await api('/rest/v1/projects',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({name,code,description})});home()}catch(e){npMsg.textContent=e.message;npMsg.className='msg err';npSave.disabled=false}}
async function guideHome(){const sections=await api('/rest/v1/guide_sections?select=*&order=sort_order.asc');let h='<div class="wrap"><button class="back" id="bh">← Projekti</button><div class="hero"><div><h1>Uputstvo</h1><p class="sub">Interna tehnička biblioteka</p></div><div class="big">📘</div></div><div class="grid" style="margin-top:14px">';sections.forEach(s=>{h+='<div class="card guide-section" data-gs="'+s.id+'"><h2>'+esc(s.title)+'</h2><p class="sub">'+esc(s.description||'')+'</p><b style="color:var(--blue)">Otvori →</b></div>'});h+='</div></div>';shell(h);bh.onclick=home;document.querySelectorAll('[data-gs]').forEach(n=>n.onclick=()=>guideSection(n.dataset.gs))}
async function guideSection(id){const sec=(await api('/rest/v1/guide_sections?id=eq.'+encodeURIComponent(id)+'&select=*'))[0],items=await api('/rest/v1/guide_items?section_id=eq.'+encodeURIComponent(id)+'&select=*&order=sort_order.asc,created_at.asc');let h='<div class="wrap"><button class="back" id="bg">← Uputstvo</button><div class="hero"><div><h1>'+esc(sec.title)+'</h1><p class="sub">'+esc(sec.description||'')+'</p></div>'+(isAdmin()?'<button class="btn" id="guideAdd">＋ Dodaj</button>':'')+'</div><div class="rows" style="margin-top:14px">';h+=items.length?items.map(x=>'<div class="row guide-row" data-gi="'+x.id+'"><div><b>'+esc(x.title)+'</b><small>'+esc(x.description||'')+'</small></div><b>Otvori →</b></div>').join(''):'<div class="notice">Još nema dodatog sadržaja.</div>';h+='</div></div>';shell(h);bg.onclick=guideHome;document.querySelectorAll('[data-gi]').forEach(n=>n.onclick=()=>guideItem(n.dataset.gi));if(isAdmin())guideAdd.onclick=()=>guideItemForm(sec)}
function guideItemForm(sec){let h='<div class="wrap"><button class="back" id="bs">← '+esc(sec.title)+'</button><h1>Dodaj sadržaj</h1><div class="form"><div class="field"><label>Naslov</label><input id="giTitle"></div><div class="field"><label>Kratak opis</label><input id="giDesc"></div><div class="field"><label>Sadržaj / napomena</label><textarea id="giContent" style="min-height:180px"></textarea></div><button class="btn" id="giSave">Dodaj</button><div id="giMsg" class="msg"></div></div></div>';shell(h);bs.onclick=()=>guideSection(sec.id);giSave.onclick=()=>saveGuideItem(sec.id)}
async function saveGuideItem(sectionId){const title=giTitle.value.trim();if(!title){giMsg.textContent='Unesi naslov.';giMsg.className='msg err';return}giSave.disabled=true;try{await api('/rest/v1/guide_items',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({section_id:sectionId,title,description:giDesc.value.trim()||null,content:giContent.value.trim()||null,created_by:session.user.id})});guideSection(sectionId)}catch(e){giMsg.textContent=e.message;giMsg.className='msg err';giSave.disabled=false}}
async function guideItem(id){const x=(await api('/rest/v1/guide_items?id=eq.'+encodeURIComponent(id)+'&select=*,guide_sections(id,title)'))[0];let h='<div class="wrap"><button class="back" id="bs">← '+esc(x.guide_sections?.title||'Uputstvo')+'</button><h1>'+esc(x.title)+'</h1>'+(x.description?'<p class="sub">'+esc(x.description)+'</p>':'')+'<div class="form"><div style="white-space:pre-wrap;line-height:1.55">'+esc(x.content||'Sadržaj još nije unet.')+'</div></div></div>';shell(h);bs.onclick=()=>guideSection(x.section_id)}
async function manageUsers(){const us=await api('/rest/v1/profiles?select=id,email,full_name,role,active,created_at&order=created_at.asc');let h='<div class="wrap"><button class="back" id="bh">← Projekti</button><h1>Korisnici i prava</h1><p class="sub">Admin može da odobri nalog i promeni ulogu.</p><div class="rows">';h+=us.map(u=>'<div class="row user-row"><div><b>'+esc(u.full_name||u.email||u.id)+'</b><small>'+esc(u.email||'')+'</small></div><div class="btnrow"><select data-role="'+u.id+'"><option value="admin" '+(u.role==='admin'?'selected':'')+'>admin</option><option value="member" '+(u.role==='member'?'selected':'')+'>member</option><option value="viewer" '+(u.role==='viewer'?'selected':'')+'>viewer</option></select><label><input type="checkbox" data-active="'+u.id+'" '+(u.active?'checked':'')+'> aktivan</label><button class="btn small" data-save-user="'+u.id+'">Sačuvaj</button></div></div>').join('');h+='</div></div>';shell(h);bh.onclick=home;document.querySelectorAll('[data-save-user]').forEach(b=>b.onclick=()=>saveUser(b.dataset.saveUser))}
async function saveUser(id){const role=document.querySelector('[data-role="'+id+'"]').value,active=document.querySelector('[data-active="'+id+'"]').checked;try{await api('/rest/v1/profiles?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({role,active})});manageUsers()}catch(e){alert(e.message)}}
async function project(id){const p=(await api('/rest/v1/projects?id=eq.'+encodeURIComponent(id)+'&select=*'))[0];currentProject=p;if(p?.code==='cvetojevac-sobovica')return corridorHome();const rs=await api('/rest/v1/rlcs?project_id=eq.'+encodeURIComponent(id)+'&select=*&order=code.asc');let comp=[],tasks=[];const rids=rs.map(r=>r.id);if(rids.length){comp=await api('/rest/v1/components?rlc_id=in.('+rids.join(',')+')&select=id,rlc_id');const cids=comp.map(c=>c.id);if(cids.length)tasks=await api('/rest/v1/component_tasks?component_id=in.('+cids.join(',')+')&select=component_id,is_complete')};const pct=r=>{const ids=comp.filter(c=>c.rlc_id===r.id).map(c=>c.id),tt=tasks.filter(t=>ids.includes(t.component_id));return tt.length?Math.round(tt.filter(t=>t.is_complete).length/tt.length*100):0};let h='<div class="wrap"><button class="back" id="bh">← Projekti</button><div class="hero"><div><h1>'+esc(p.name)+'</h1><p class="sub">Centralna evidencija radova</p></div></div><div class="rlcgrid">';rs.forEach(r=>{const pc=pct(r);h+='<div class="tile" data-r="'+r.id+'"><h3>'+esc(r.code)+'</h3><p class="sub">'+esc(r.design_name||'')+' · '+esc(r.chainage||'')+'</p><div class="progress"><i style="width:'+pc+'%"></i></div><b>'+pc+'%</b></div>'});h+='</div></div>';shell(h);bh.onclick=home;document.querySelectorAll('[data-r]').forEach(n=>n.onclick=()=>rlc(n.dataset.r))}
